### ISSUE TITLE
There have Storage type XSS vulnerability that can excute javascript

### ISSUE THREAD

**Issue by K1ns0** [VictorAlagwu/CMSsite#2]
Here is a XSS vulnerability.
No login required.
Just need to open an article and comment on it.
For example，this article：
![c61 37_fu3 sl6pal0b0](https://user-images.githubusercontent.com/31464698/44326831-82690780-a48f-11e8-999c-5eeb3a700843.png)

#######################################################################
Add comments here---->
![image](https://user-images.githubusercontent.com/31464698/44326981-f2778d80-a48f-11e8-96cb-a3eefe34fb55.png)

#######################################################################
When I click Submit，it will pop up XSS---->
![image](https://user-images.githubusercontent.com/31464698/44327025-13d87980-a490-11e8-9b3f-85b51f26505d.png)

#######################################################################
Here is the page source code---->
![image](https://user-images.githubusercontent.com/31464698/44327235-9b25ed00-a490-11e8-822a-92407c35acbf.png)

And opening comments in the background will also pop up XSS.

**Comment by VictorAlagwu** [comment]
Thanks, for taking out time to run this program, this project was developed when I first started learning PHP, that is about two years ago, but you can send a pull request that contains a fix to this issue, would really appreciate
Thanks.

**Comment by K1ns0** [comment]
I am also learning this knowledge. I can just practise, Lift a finger.
Thanks for your CMS :>)
