### ISSUE TITLE
category.php exists sql injection vulnerability

### ISSUE THREAD

**Issue by byck01** [VictorAlagwu/CMSsite#6]
* 1.$category is obtained by $GET['cat_id'], passed to the mysqli_query function without any filtering; causing sql injection vulnerability
![2019-02-27 2 39 20](https://user-images.githubusercontent.com/38834848/53470802-ab510180-3a9d-11e9-8804-d4a892e2210b.png)

* 2.payload
```
http://localhost/CMSsite/category.php?cat_id=1%20and%20(sleep(20))
```

**Comment by VictorAlagwu** [comment]
Thanks for the review, you can send a PR that will fix the issue and I will review it.

**Comment by byck01** [comment]
OK! Already sent you PR

**Comment by VictorAlagwu** [comment]
#7

**Comment by VictorAlagwu** [comment]
#7 Resolved
